[package]
name = "ignite-client-rust"
version = "0.0.1"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
tokio = { version = "1.34.0", features = ["full"] }
bytes = "1.5.0"
matches = "0.1.10"

[dev-dependencies]
tokio-test = "0.4"
