name: rust clippy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - run: cargo clippy
